# Generated by Django 2.2.23 on 2021-09-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='applicant_id',
            field=models.CharField(db_index=True, help_text='', max_length=128, verbose_name='Applicant ID'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='first_name',
            field=models.CharField(db_index=True, help_text='', max_length=128, verbose_name='Applicant First Name'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='last_name',
            field=models.CharField(db_index=True, help_text='', max_length=128, verbose_name='Applicant Last Name'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='reviewer_first_name',
            field=models.CharField(db_index=True, help_text='', max_length=128, verbose_name='Reviewer First Name'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='reviewer_last_name',
            field=models.CharField(db_index=True, help_text='', max_length=128, verbose_name='Reviewer Last Name'),
        ),
    ]
